### ISSUE TITLE
Display ontology / resource classes as visualized graph

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/dsp-app#238]
**Is your feature request related to a problem? Please describe.**
In the ontology editor I wanted to display the resource classes as visual graph like the on in the GraphDB interface. It should list the resource classes with the defined properties and show the connections between the resource classes.

![Screen Shot 2020-01-13 at 14 11 49](https://user-images.githubusercontent.com/4253580/72258592-befe4b80-360e-11ea-9546-ca4b648b11a5.png)

**I tried the following tools:**

**[d3-force](https://observablehq.com/collection/@d3/d3-force)**
The implementation of d3js in Angular isn't an issue as the following tutorial shows:
[Integrating D3js with Angular 5.0](https://medium.com/@balramchavan/integrating-d3js-with-angular-5-0-848ed45a8e19)

To work with our data, we have to convert json-ld to an array of nodes and links. There's another tutorial about the angular / d3 setup: [Visualizing Data with Angular and D3](https://medium.com/netscape/visualizing-data-with-angular-and-d3-209dde784aeb)

But at the end, the output is too complex!

**[jsonld-vis](https://www.npmjs.com/package/jsonld-vis)**
d3 plugin which supports json-ld directly and it's the same tool, which is used in [JSON-LD Playground](https://json-ld.org/playground/). But it's outdated and shows too much information. The visualized structure is not simple anymore.

![Screen Shot 2020-01-13 at 14 31 43](https://user-images.githubusercontent.com/4253580/72259730-75633000-3611-11ea-80c3-0f553087a639.png)

**[d3-graphviz](https://github.com/magjac/d3-graphviz)**
d3 plugin with a simple output, but it needs a good json-ld conversion first.

**echarts, three.js and others**
I had a look on other tools, mentioned in this article:
[11 Javascript Data Visualization Libraries for 2019](https://blog.bitsrc.io/11-javascript-charts-and-data-visualization-libraries-for-2018-f01a283a5727)

- [echarts example with Angular](https://xieziyu.github.io/ngx-echarts/#/home)

**Describe the solution you'd like**
It should be a simple visualization of the resource classes and the connection from one to the other (if it's defined). Similar to the phpMyAdmin designer tool.

![phpmyadmin-designer](https://user-images.githubusercontent.com/4253580/72259360-8b242580-3610-11ea-8f6f-789d572a7c11.png)

**Additional context**
At the moment we don't have the time to work on visual graph solution and I'll integrate a simple list for the resource classes. But we should come back to this issue later on.

**Comment by flavens** [comment]
Project example - Sparql visualizer with D3.js
https://github.com/MadsHolten/sparql-visualizer

**Comment by SepidehAlassi** [comment]
[DSP-83](https://dasch.myjetbrains.com/youtrack/issue/DSP-83) is the user story corresponding to this issue.

**Comment by musicEnfanthen** [comment]
> 
> 
> Project example - Sparql visualizer with D3.js
> https://github.com/MadsHolten/sparql-visualizer

FYI, recently I adapted MadsHolten's project to Angular 8 for our Webern prototype: https://edition.anton-webern.ch/edition/composition/op25/graph

**Comment by flavens** [comment]
@SepidehAlassi is this issue still opened or should it be closed?

**Comment by SepidehAlassi** [comment]
well, it is implemented but not merged to knora-app yet. Should we close it once it is merged?

**Comment by flavens** [comment]
> well, it is implemented but not merged to knora-app yet. Should we close it once it is merged?

Yes we can. In order to remember it, could you mention to close this issue in the YT issue? thanks

**Comment by SepidehAlassi** [comment]
> Could you mention to close this issue in the YT issue? thanks

Sure!
